In [44]:
import pandas as pd

df = pd.read_csv('data.csv')
df.head()

                  time  offerType
0  2022-03-07 08:30:00          3
1  2022-03-07 08:30:07          2
2  2022-03-07 08:31:17          3
3  2022-03-07 08:32:53          3
4  2022-03-07 08:36:20          2

In [45]:
df["hour"] = df["time"].apply(lambda x: (x.split(" ")[1][:2]))
df.head()

                  time  offerType hour
0  2022-03-07 08:30:00          3   08
1  2022-03-07 08:30:07          2   08
2  2022-03-07 08:31:17          3   08
3  2022-03-07 08:32:53          3   08
4  2022-03-07 08:36:20          2   08

In [46]:
df.groupby("hour").count() / 5

      time  offerType
hour
08    22.4       22.4
09    92.0       92.0
10    90.4       90.4
11    53.2       53.2
12    39.2       39.2
13    23.6       23.6
14    82.4       82.4
15    89.2       89.2
16    36.2       36.2
17    23.0       23.0

In [42]:
foo = [
        0.0391, 0.0901, 0.0781, 0.0641, 0.0981, 0.0811, 0.024, 0.03, 0.0451, 0.019, 0.03, 0.0701, 0.0751, 0.0776, 0.0861,
        0.032, 0.026, 0.0381
    ]

foo = [i * 534 for i in foo]

[20.8794,
 48.1134,
 41.705400000000004,
 34.229400000000005,
 52.385400000000004,
 43.3074,
 12.816,
 16.02,
 24.0834,
 10.145999999999999,
 16.02,
 37.4334,
 40.1034,
 41.4384,
 45.977399999999996,
 17.088,
 13.883999999999999,
 20.3454]

In [1]:
from simulation import CallCenter
from simulation import  Core


s = [[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0],[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0],[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0],[0,1,1,1,1,1,1,1,1,0,0,0,1,1,1,1,1,1],[0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0],[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0]]


sim = CallCenter.CallCenterCase(s)
res = sim.run(10)

In [2]:
res.asDict()

{'perf_metric': 73.255919894,
 'avgQualityOfService': 86.72669,
 'avgAgentUtilizationRate': 59.785149788,
 'avgOfAverageTimeInSystem': 5.100554255648918,
 'stdOfAverageTimeInSystem': 0.17297975209784136,
 'maxOfAverageTimeInSystem': 5.29709088163749,
 'minOfAverageTimeInSystem': 4.734782701640567,
 'avgOfAverageTimeInQueue': 0.7772537833594175,
 'stdOfAverageTimeInQueue': 0.056737446428684,
 'maxOfAverageTimeInQueue': 0.8828630754625196,
 'minOfAverageTimeInQueue': 0.6906134742370666,
 'avgOfAverageServiceTime': 4.941402915031203,
 'stdOfAverageServiceTime': 0.14993788982847467,
 'maxOfAverageServiceTime': 5.084679721306001,
 'minOfAverageServiceTime': 4.575959658436291,
 'avgOfAverageCustomerArrived': 523.0,
 'stdOfAverageCustomerArrived': 20.282997806044353,
 'maxOfAverageCustomerArrived': 560.0,
 'minOfAverageCustomerArrived': 484.0,
 'avgOfAverageCustomerServed': 457.0,
 'stdOfAverageCustomerServed': 17.933209417167916,
 'maxOfAverageCustomerServed': 483.0,
 'minOfAverageCustomerServed': 423.0,
 'avgOfAverageQueueLength': 0.7745403196916396,
 'stdOfAverageQueueLength': 0.07492297832807122,
 'maxOfAverageQueueLength': 0.899020025222466,
 'minOfAverageQueueLength': 0.6385270879665338,
 'avgRenegeRate': 6.779631431617143,
 'stdRenegeRate': 0.7436621583890307,
 'maxRenegeRate': 8.055009823182711,
 'minRenegeRate': 5.6672760511883,
 'avgBulkRate': 5.31953302755279,
 'stdBulkRate': 1.0899015699899504,
 'maxBulkRate': 6.679389312977099,
 'minBulkRate': 3.35195530726257}

In [6]:
(61 + 83 + 33) / 3

59.0

In [43]:
import pandas as pd
import numpy as np
import datetime


__priorityCumDist = [0.03, 0.06, 0.57, 0.98, 1.  ]  # the discrete distribution of customer priority (offer type)

def __determineOfferType() -> int:
    prob = np.random.random()
    for index in range(len(__priorityCumDist)):
        cumProb = __priorityCumDist[index]
        if prob <= cumProb:
            return index

res = []
offerType = []
for i in range(5):
    baseT = datetime.datetime(2022, 3, 7 + i, 8, 30, 0)
    t = 0
    while t <= 3600 * 9:
        time = baseT + datetime.timedelta(seconds=t)
        offerType.append(__determineOfferType())

        textTime = time.strftime("%Y-%m-%d %H:%M:%S")
        res.append(textTime)
        next = CallCenter.CallCenterCase.generateInterArrivalTime(t)
        t += next


df = pd.DataFrame({"time": res, "offerType": offerType}, dtype=str)
df.to_csv("data.csv", index=False)
df.head()

                  time offerType
0  2022-03-07 08:30:00         3
1  2022-03-07 08:30:07         2
2  2022-03-07 08:31:17         3
3  2022-03-07 08:32:53         3
4  2022-03-07 08:36:20         2

In [37]:
import datetime

baseT = datetime.datetime(2022, 3, 7, 8, 30, 0)
next = CallCenter.CallCenterCase.generateInterArrivalTime(270)
baseT + datetime.timedelta(seconds=next)

datetime.datetime(2022, 3, 7, 8, 32, 13, 15955)

In [2]:
q = Core.AppPriorityQueue()

q.enqueue(1, 1)
q.enqueue(2, 2)
q.enqueue(3, 3)
q.tryDequeueItem(2)

while  q.empty() == False:
    print(q.dequeue())

1
3

In [4]:
paperSchedule = [
    [1, 1, 1, 0,0,0, 1,1,1, 0,0,0, 1,1,1, 0,0,0] for i in range(14)
]   

paperSchedule.append([
    1 for i in range(16)
] + [0, 0])

assert len(paperSchedule) == 15

case = CallCenter.CallCenterCase(paperSchedule)
res = case.run(100)
res.summaryData

{'avgQualityOfService': 59.25612799999999,
 'avgAgentUtilizationRate': 49.072821,
 'avgMaxTimeInQueue': 60.00000000000037,
 'avgAvgTimeInQueue': 25.91241639965548,
 'avgMaxServiceTime': 1483.4714480769765,
 'avgAvgServiceTime': 304.1318127399357,
 'avgCustomerArrived': 534.93,
 'avgCustomerServed': 316.93,
 'maxMaxQueueLength': (10,),
 'avgRenegeRate': 0.4070631055799906,
 'avgAvgQueueLengthOverTime': 0.5124733153561659}

In [3]:
import numpy as np

arrRate = np.array([
        0.0391, 0.0901, 0.0781, 0.0641, 0.0981, 0.0811, 0.024, 0.03, 0.0451, 0.019, 0.03, 0.0701, 0.0751, 0.0776, 0.0861,
        0.032, 0.026, 0.0381
    ] )

arr = arrRate * 534
arr

array([20.8794, 48.1134, 41.7054, 34.2294, 52.3854, 43.3074, 12.816 ,
       16.02  , 24.0834, 10.146 , 16.02  , 37.4334, 40.1034, 41.4384,
       45.9774, 17.088 , 13.884 , 20.3454])

In [5]:
None <= 1

TypeError: '<=' not supported between instances of 'NoneType' and 'int'

In [4]:
arr / 30

array([0.69598, 1.60378, 1.39018, 1.14098, 1.74618, 1.44358, 0.4272 ,
       0.534  , 0.80278, 0.3382 , 0.534  , 1.24778, 1.33678, 1.38128,
       1.53258, 0.5696 , 0.4628 , 0.67818])

In [8]:
total = 544.2
stayed= total * (1 - (15.7 + 16.6) / 100)
stayed

368.4234000000001

In [9]:
0.8 * stayed

294.73872000000006